
favicon: "/_media/alf-128.png"
logo: "/_media/alf-128.png"
title: Alf-in₃ - Automated Logic Framework Intelligent & Efficient
footer: "Alf-in₃ • Automated Logic Framework Intelligent & Efficient • © 2026 by chzb • Powered by <a href='https://a3.services' target='_blank'>a3.services</a>"

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark  # Toto prepne tému na tmavú

include:
  - _media

